/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps_client_go

import (
	"encoding/json"
)

// checks if the ProblemDetails404 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProblemDetails404{}

// ProblemDetails404 struct for ProblemDetails404
type ProblemDetails404 struct {
	Code *string `json:"code,omitempty"`
	// エラーの内容
	Message *string `json:"message,omitempty"`
}

// NewProblemDetails404 instantiates a new ProblemDetails404 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProblemDetails404() *ProblemDetails404 {
	this := ProblemDetails404{}
	return &this
}

// NewProblemDetails404WithDefaults instantiates a new ProblemDetails404 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProblemDetails404WithDefaults() *ProblemDetails404 {
	this := ProblemDetails404{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ProblemDetails404) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProblemDetails404) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ProblemDetails404) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ProblemDetails404) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ProblemDetails404) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProblemDetails404) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ProblemDetails404) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ProblemDetails404) SetMessage(v string) {
	o.Message = &v
}

func (o ProblemDetails404) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProblemDetails404) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableProblemDetails404 struct {
	value *ProblemDetails404
	isSet bool
}

func (v NullableProblemDetails404) Get() *ProblemDetails404 {
	return v.value
}

func (v *NullableProblemDetails404) Set(val *ProblemDetails404) {
	v.value = val
	v.isSet = true
}

func (v NullableProblemDetails404) IsSet() bool {
	return v.isSet
}

func (v *NullableProblemDetails404) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProblemDetails404(val *ProblemDetails404) *NullableProblemDetails404 {
	return &NullableProblemDetails404{value: val, isSet: true}
}

func (v NullableProblemDetails404) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProblemDetails404) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


