/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServerZone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerZone{}

// ServerZone ゾーン情報
type ServerZone struct {
	// ゾーンコード * tk1 東京第1 * tk2 東京第2 * tk3 東京第3 * os1 大阪第1 * os2 大阪第2 * os3 大阪第3 * is1 石狩第1
	Code string `json:"code"`
	// ゾーン名称
	Name string `json:"name"`
}

type _ServerZone ServerZone

// NewServerZone instantiates a new ServerZone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerZone(code string, name string) *ServerZone {
	this := ServerZone{}
	this.Code = code
	this.Name = name
	return &this
}

// NewServerZoneWithDefaults instantiates a new ServerZone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerZoneWithDefaults() *ServerZone {
	this := ServerZone{}
	return &this
}

// GetCode returns the Code field value
func (o *ServerZone) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ServerZone) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ServerZone) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *ServerZone) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServerZone) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServerZone) SetName(v string) {
	o.Name = v
}

func (o ServerZone) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerZone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ServerZone) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServerZone := _ServerZone{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServerZone)

	if err != nil {
		return err
	}

	*o = ServerZone(varServerZone)

	return err
}

type NullableServerZone struct {
	value *ServerZone
	isSet bool
}

func (v NullableServerZone) Get() *ServerZone {
	return v.value
}

func (v *NullableServerZone) Set(val *ServerZone) {
	v.value = val
	v.isSet = true
}

func (v NullableServerZone) IsSet() bool {
	return v.isSet
}

func (v *NullableServerZone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerZone(val *ServerZone) *NullableServerZone {
	return &NullableServerZone{value: val, isSet: true}
}

func (v NullableServerZone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerZone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


