/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps_client_go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRoleList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRoleList200Response{}

// GetRoleList200Response struct for GetRoleList200Response
type GetRoleList200Response struct {
	// データ総数
	Count int32 `json:"count"`
	// 次のページへのURL
	Next NullableString `json:"next"`
	// 前のページへのURL
	Previous NullableString `json:"previous"`
	Results []Role `json:"results"`
}

type _GetRoleList200Response GetRoleList200Response

// NewGetRoleList200Response instantiates a new GetRoleList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRoleList200Response(count int32, next NullableString, previous NullableString, results []Role) *GetRoleList200Response {
	this := GetRoleList200Response{}
	this.Count = count
	this.Next = next
	this.Previous = previous
	this.Results = results
	return &this
}

// NewGetRoleList200ResponseWithDefaults instantiates a new GetRoleList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRoleList200ResponseWithDefaults() *GetRoleList200Response {
	this := GetRoleList200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *GetRoleList200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *GetRoleList200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *GetRoleList200Response) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetRoleList200Response) GetNext() string {
	if o == nil || o.Next.Get() == nil {
		var ret string
		return ret
	}

	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRoleList200Response) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// SetNext sets field value
func (o *GetRoleList200Response) SetNext(v string) {
	o.Next.Set(&v)
}

// GetPrevious returns the Previous field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetRoleList200Response) GetPrevious() string {
	if o == nil || o.Previous.Get() == nil {
		var ret string
		return ret
	}

	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRoleList200Response) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// SetPrevious sets field value
func (o *GetRoleList200Response) SetPrevious(v string) {
	o.Previous.Set(&v)
}

// GetResults returns the Results field value
func (o *GetRoleList200Response) GetResults() []Role {
	if o == nil {
		var ret []Role
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *GetRoleList200Response) GetResultsOk() ([]Role, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *GetRoleList200Response) SetResults(v []Role) {
	o.Results = v
}

func (o GetRoleList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRoleList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["next"] = o.Next.Get()
	toSerialize["previous"] = o.Previous.Get()
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *GetRoleList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"next",
		"previous",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRoleList200Response := _GetRoleList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRoleList200Response)

	if err != nil {
		return err
	}

	*o = GetRoleList200Response(varGetRoleList200Response)

	return err
}

type NullableGetRoleList200Response struct {
	value *GetRoleList200Response
	isSet bool
}

func (v NullableGetRoleList200Response) Get() *GetRoleList200Response {
	return v.value
}

func (v *NullableGetRoleList200Response) Set(val *GetRoleList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRoleList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRoleList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRoleList200Response(val *GetRoleList200Response) *NullableGetRoleList200Response {
	return &NullableGetRoleList200Response{value: val, isSet: true}
}

func (v NullableGetRoleList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRoleList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


