/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakuravps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PutServerIpv4PtrRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutServerIpv4PtrRequest{}

// PutServerIpv4PtrRequest struct for PutServerIpv4PtrRequest
type PutServerIpv4PtrRequest struct {
	// ホスト名
	Hostname string `json:"hostname"`
}

type _PutServerIpv4PtrRequest PutServerIpv4PtrRequest

// NewPutServerIpv4PtrRequest instantiates a new PutServerIpv4PtrRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutServerIpv4PtrRequest(hostname string) *PutServerIpv4PtrRequest {
	this := PutServerIpv4PtrRequest{}
	this.Hostname = hostname
	return &this
}

// NewPutServerIpv4PtrRequestWithDefaults instantiates a new PutServerIpv4PtrRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutServerIpv4PtrRequestWithDefaults() *PutServerIpv4PtrRequest {
	this := PutServerIpv4PtrRequest{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *PutServerIpv4PtrRequest) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *PutServerIpv4PtrRequest) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *PutServerIpv4PtrRequest) SetHostname(v string) {
	o.Hostname = v
}

func (o PutServerIpv4PtrRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutServerIpv4PtrRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hostname"] = o.Hostname
	return toSerialize, nil
}

func (o *PutServerIpv4PtrRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hostname",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutServerIpv4PtrRequest := _PutServerIpv4PtrRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutServerIpv4PtrRequest)

	if err != nil {
		return err
	}

	*o = PutServerIpv4PtrRequest(varPutServerIpv4PtrRequest)

	return err
}

type NullablePutServerIpv4PtrRequest struct {
	value *PutServerIpv4PtrRequest
	isSet bool
}

func (v NullablePutServerIpv4PtrRequest) Get() *PutServerIpv4PtrRequest {
	return v.value
}

func (v *NullablePutServerIpv4PtrRequest) Set(val *PutServerIpv4PtrRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutServerIpv4PtrRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutServerIpv4PtrRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutServerIpv4PtrRequest(val *PutServerIpv4PtrRequest) *NullablePutServerIpv4PtrRequest {
	return &NullablePutServerIpv4PtrRequest{value: val, isSet: true}
}

func (v NullablePutServerIpv4PtrRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutServerIpv4PtrRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


