/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps_client_go

import (
	"encoding/json"
)

// checks if the PostServerShutdownRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostServerShutdownRequest{}

// PostServerShutdownRequest struct for PostServerShutdownRequest
type PostServerShutdownRequest struct {
	// 強制停止を行うか
	Force *bool `json:"force,omitempty"`
}

// NewPostServerShutdownRequest instantiates a new PostServerShutdownRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostServerShutdownRequest() *PostServerShutdownRequest {
	this := PostServerShutdownRequest{}
	var force bool = false
	this.Force = &force
	return &this
}

// NewPostServerShutdownRequestWithDefaults instantiates a new PostServerShutdownRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostServerShutdownRequestWithDefaults() *PostServerShutdownRequest {
	this := PostServerShutdownRequest{}
	var force bool = false
	this.Force = &force
	return &this
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *PostServerShutdownRequest) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostServerShutdownRequest) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *PostServerShutdownRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *PostServerShutdownRequest) SetForce(v bool) {
	o.Force = &v
}

func (o PostServerShutdownRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostServerShutdownRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	return toSerialize, nil
}

type NullablePostServerShutdownRequest struct {
	value *PostServerShutdownRequest
	isSet bool
}

func (v NullablePostServerShutdownRequest) Get() *PostServerShutdownRequest {
	return v.value
}

func (v *NullablePostServerShutdownRequest) Set(val *PostServerShutdownRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostServerShutdownRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostServerShutdownRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostServerShutdownRequest(val *PostServerShutdownRequest) *NullablePostServerShutdownRequest {
	return &NullablePostServerShutdownRequest{value: val, isSet: true}
}

func (v NullablePostServerShutdownRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostServerShutdownRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


