/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps_client_go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NfsServerIpv4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NfsServerIpv4{}

// NfsServerIpv4 struct for NfsServerIpv4
type NfsServerIpv4 struct {
	// アドレス
	Address string `json:"address"`
	// サブネットマスク
	Netmask string `json:"netmask"`
}

type _NfsServerIpv4 NfsServerIpv4

// NewNfsServerIpv4 instantiates a new NfsServerIpv4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNfsServerIpv4(address string, netmask string) *NfsServerIpv4 {
	this := NfsServerIpv4{}
	this.Address = address
	this.Netmask = netmask
	return &this
}

// NewNfsServerIpv4WithDefaults instantiates a new NfsServerIpv4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNfsServerIpv4WithDefaults() *NfsServerIpv4 {
	this := NfsServerIpv4{}
	return &this
}

// GetAddress returns the Address field value
func (o *NfsServerIpv4) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NfsServerIpv4) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NfsServerIpv4) SetAddress(v string) {
	o.Address = v
}

// GetNetmask returns the Netmask field value
func (o *NfsServerIpv4) GetNetmask() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Netmask
}

// GetNetmaskOk returns a tuple with the Netmask field value
// and a boolean to check if the value has been set.
func (o *NfsServerIpv4) GetNetmaskOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Netmask, true
}

// SetNetmask sets field value
func (o *NfsServerIpv4) SetNetmask(v string) {
	o.Netmask = v
}

func (o NfsServerIpv4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NfsServerIpv4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["netmask"] = o.Netmask
	return toSerialize, nil
}

func (o *NfsServerIpv4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"netmask",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNfsServerIpv4 := _NfsServerIpv4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNfsServerIpv4)

	if err != nil {
		return err
	}

	*o = NfsServerIpv4(varNfsServerIpv4)

	return err
}

type NullableNfsServerIpv4 struct {
	value *NfsServerIpv4
	isSet bool
}

func (v NullableNfsServerIpv4) Get() *NfsServerIpv4 {
	return v.value
}

func (v *NullableNfsServerIpv4) Set(val *NfsServerIpv4) {
	v.value = val
	v.isSet = true
}

func (v NullableNfsServerIpv4) IsSet() bool {
	return v.isSet
}

func (v *NullableNfsServerIpv4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNfsServerIpv4(val *NfsServerIpv4) *NullableNfsServerIpv4 {
	return &NullableNfsServerIpv4{value: val, isSet: true}
}

func (v NullableNfsServerIpv4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNfsServerIpv4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


