/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServerInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerInterface{}

// ServerInterface struct for ServerInterface
type ServerInterface struct {
	// id
	Id int32 `json:"id"`
	// NIC名称
	Device string `json:"device"`
	// グローバルネットワークと接続可能か
	ConnectableToGlobalNetwork bool `json:"connectable_to_global_network"`
	// インターフェースの接続先
	ConnectTo NullableString `json:"connect_to"`
	// MACアドレス
	Mac string `json:"mac"`
	// スイッチID
	SwitchId NullableInt32 `json:"switch_id"`
}

type _ServerInterface ServerInterface

// NewServerInterface instantiates a new ServerInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerInterface(id int32, device string, connectableToGlobalNetwork bool, connectTo NullableString, mac string, switchId NullableInt32) *ServerInterface {
	this := ServerInterface{}
	this.Id = id
	this.Device = device
	this.ConnectableToGlobalNetwork = connectableToGlobalNetwork
	this.ConnectTo = connectTo
	this.Mac = mac
	this.SwitchId = switchId
	return &this
}

// NewServerInterfaceWithDefaults instantiates a new ServerInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerInterfaceWithDefaults() *ServerInterface {
	this := ServerInterface{}
	return &this
}

// GetId returns the Id field value
func (o *ServerInterface) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ServerInterface) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ServerInterface) SetId(v int32) {
	o.Id = v
}

// GetDevice returns the Device field value
func (o *ServerInterface) GetDevice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *ServerInterface) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *ServerInterface) SetDevice(v string) {
	o.Device = v
}

// GetConnectableToGlobalNetwork returns the ConnectableToGlobalNetwork field value
func (o *ServerInterface) GetConnectableToGlobalNetwork() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ConnectableToGlobalNetwork
}

// GetConnectableToGlobalNetworkOk returns a tuple with the ConnectableToGlobalNetwork field value
// and a boolean to check if the value has been set.
func (o *ServerInterface) GetConnectableToGlobalNetworkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectableToGlobalNetwork, true
}

// SetConnectableToGlobalNetwork sets field value
func (o *ServerInterface) SetConnectableToGlobalNetwork(v bool) {
	o.ConnectableToGlobalNetwork = v
}

// GetConnectTo returns the ConnectTo field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ServerInterface) GetConnectTo() string {
	if o == nil || o.ConnectTo.Get() == nil {
		var ret string
		return ret
	}

	return *o.ConnectTo.Get()
}

// GetConnectToOk returns a tuple with the ConnectTo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServerInterface) GetConnectToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectTo.Get(), o.ConnectTo.IsSet()
}

// SetConnectTo sets field value
func (o *ServerInterface) SetConnectTo(v string) {
	o.ConnectTo.Set(&v)
}

// GetMac returns the Mac field value
func (o *ServerInterface) GetMac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mac
}

// GetMacOk returns a tuple with the Mac field value
// and a boolean to check if the value has been set.
func (o *ServerInterface) GetMacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mac, true
}

// SetMac sets field value
func (o *ServerInterface) SetMac(v string) {
	o.Mac = v
}

// GetSwitchId returns the SwitchId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ServerInterface) GetSwitchId() int32 {
	if o == nil || o.SwitchId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.SwitchId.Get()
}

// GetSwitchIdOk returns a tuple with the SwitchId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServerInterface) GetSwitchIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SwitchId.Get(), o.SwitchId.IsSet()
}

// SetSwitchId sets field value
func (o *ServerInterface) SetSwitchId(v int32) {
	o.SwitchId.Set(&v)
}

func (o ServerInterface) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["device"] = o.Device
	toSerialize["connectable_to_global_network"] = o.ConnectableToGlobalNetwork
	toSerialize["connect_to"] = o.ConnectTo.Get()
	toSerialize["mac"] = o.Mac
	toSerialize["switch_id"] = o.SwitchId.Get()
	return toSerialize, nil
}

func (o *ServerInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"device",
		"connectable_to_global_network",
		"connect_to",
		"mac",
		"switch_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServerInterface := _ServerInterface{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServerInterface)

	if err != nil {
		return err
	}

	*o = ServerInterface(varServerInterface)

	return err
}

type NullableServerInterface struct {
	value *ServerInterface
	isSet bool
}

func (v NullableServerInterface) Get() *ServerInterface {
	return v.value
}

func (v *NullableServerInterface) Set(val *ServerInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableServerInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableServerInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerInterface(val *ServerInterface) *NullableServerInterface {
	return &NullableServerInterface{value: val, isSet: true}
}

func (v NullableServerInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


