/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PutServerVideoDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutServerVideoDeviceRequest{}

// PutServerVideoDeviceRequest struct for PutServerVideoDeviceRequest
type PutServerVideoDeviceRequest struct {
	// ビデオデバイスの種類
	Type string `json:"type"`
}

type _PutServerVideoDeviceRequest PutServerVideoDeviceRequest

// NewPutServerVideoDeviceRequest instantiates a new PutServerVideoDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutServerVideoDeviceRequest(type_ string) *PutServerVideoDeviceRequest {
	this := PutServerVideoDeviceRequest{}
	this.Type = type_
	return &this
}

// NewPutServerVideoDeviceRequestWithDefaults instantiates a new PutServerVideoDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutServerVideoDeviceRequestWithDefaults() *PutServerVideoDeviceRequest {
	this := PutServerVideoDeviceRequest{}
	return &this
}

// GetType returns the Type field value
func (o *PutServerVideoDeviceRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PutServerVideoDeviceRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PutServerVideoDeviceRequest) SetType(v string) {
	o.Type = v
}

func (o PutServerVideoDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutServerVideoDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PutServerVideoDeviceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutServerVideoDeviceRequest := _PutServerVideoDeviceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutServerVideoDeviceRequest)

	if err != nil {
		return err
	}

	*o = PutServerVideoDeviceRequest(varPutServerVideoDeviceRequest)

	return err
}

type NullablePutServerVideoDeviceRequest struct {
	value *PutServerVideoDeviceRequest
	isSet bool
}

func (v NullablePutServerVideoDeviceRequest) Get() *PutServerVideoDeviceRequest {
	return v.value
}

func (v *NullablePutServerVideoDeviceRequest) Set(val *PutServerVideoDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutServerVideoDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutServerVideoDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutServerVideoDeviceRequest(val *PutServerVideoDeviceRequest) *NullablePutServerVideoDeviceRequest {
	return &NullablePutServerVideoDeviceRequest{value: val, isSet: true}
}

func (v NullablePutServerVideoDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutServerVideoDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


