/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps_client_go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetServerVideoDevice200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetServerVideoDevice200Response{}

// GetServerVideoDevice200Response struct for GetServerVideoDevice200Response
type GetServerVideoDevice200Response struct {
	// ビデオデバイスの種類
	Type string `json:"type"`
}

type _GetServerVideoDevice200Response GetServerVideoDevice200Response

// NewGetServerVideoDevice200Response instantiates a new GetServerVideoDevice200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetServerVideoDevice200Response(type_ string) *GetServerVideoDevice200Response {
	this := GetServerVideoDevice200Response{}
	this.Type = type_
	return &this
}

// NewGetServerVideoDevice200ResponseWithDefaults instantiates a new GetServerVideoDevice200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetServerVideoDevice200ResponseWithDefaults() *GetServerVideoDevice200Response {
	this := GetServerVideoDevice200Response{}
	return &this
}

// GetType returns the Type field value
func (o *GetServerVideoDevice200Response) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetServerVideoDevice200Response) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetServerVideoDevice200Response) SetType(v string) {
	o.Type = v
}

func (o GetServerVideoDevice200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetServerVideoDevice200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GetServerVideoDevice200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetServerVideoDevice200Response := _GetServerVideoDevice200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetServerVideoDevice200Response)

	if err != nil {
		return err
	}

	*o = GetServerVideoDevice200Response(varGetServerVideoDevice200Response)

	return err
}

type NullableGetServerVideoDevice200Response struct {
	value *GetServerVideoDevice200Response
	isSet bool
}

func (v NullableGetServerVideoDevice200Response) Get() *GetServerVideoDevice200Response {
	return v.value
}

func (v *NullableGetServerVideoDevice200Response) Set(val *GetServerVideoDevice200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetServerVideoDevice200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetServerVideoDevice200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetServerVideoDevice200Response(val *GetServerVideoDevice200Response) *NullableGetServerVideoDevice200Response {
	return &NullableGetServerVideoDevice200Response{value: val, isSet: true}
}

func (v NullableGetServerVideoDevice200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetServerVideoDevice200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


