/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HealthCheckPop3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthCheckPop3{}

// HealthCheckPop3 struct for HealthCheckPop3
type HealthCheckPop3 struct {
	// 監視方法
	Protocol string `json:"protocol"`
	// ポート番号
	Port int32 `json:"port"`
	// チェック間隔(分)
	IntervalMinutes int32 `json:"interval_minutes"`
}

type _HealthCheckPop3 HealthCheckPop3

// NewHealthCheckPop3 instantiates a new HealthCheckPop3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheckPop3(protocol string, port int32, intervalMinutes int32) *HealthCheckPop3 {
	this := HealthCheckPop3{}
	this.Protocol = protocol
	this.Port = port
	this.IntervalMinutes = intervalMinutes
	return &this
}

// NewHealthCheckPop3WithDefaults instantiates a new HealthCheckPop3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheckPop3WithDefaults() *HealthCheckPop3 {
	this := HealthCheckPop3{}
	return &this
}

// GetProtocol returns the Protocol field value
func (o *HealthCheckPop3) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *HealthCheckPop3) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *HealthCheckPop3) SetProtocol(v string) {
	o.Protocol = v
}

// GetPort returns the Port field value
func (o *HealthCheckPop3) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *HealthCheckPop3) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *HealthCheckPop3) SetPort(v int32) {
	o.Port = v
}

// GetIntervalMinutes returns the IntervalMinutes field value
func (o *HealthCheckPop3) GetIntervalMinutes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IntervalMinutes
}

// GetIntervalMinutesOk returns a tuple with the IntervalMinutes field value
// and a boolean to check if the value has been set.
func (o *HealthCheckPop3) GetIntervalMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntervalMinutes, true
}

// SetIntervalMinutes sets field value
func (o *HealthCheckPop3) SetIntervalMinutes(v int32) {
	o.IntervalMinutes = v
}

func (o HealthCheckPop3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthCheckPop3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["protocol"] = o.Protocol
	toSerialize["port"] = o.Port
	toSerialize["interval_minutes"] = o.IntervalMinutes
	return toSerialize, nil
}

func (o *HealthCheckPop3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protocol",
		"port",
		"interval_minutes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthCheckPop3 := _HealthCheckPop3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthCheckPop3)

	if err != nil {
		return err
	}

	*o = HealthCheckPop3(varHealthCheckPop3)

	return err
}

type NullableHealthCheckPop3 struct {
	value *HealthCheckPop3
	isSet bool
}

func (v NullableHealthCheckPop3) Get() *HealthCheckPop3 {
	return v.value
}

func (v *NullableHealthCheckPop3) Set(val *HealthCheckPop3) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheckPop3) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheckPop3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheckPop3(val *HealthCheckPop3) *NullableHealthCheckPop3 {
	return &NullableHealthCheckPop3{value: val, isSet: true}
}

func (v NullableHealthCheckPop3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheckPop3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


