/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Switch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Switch{}

// Switch struct for Switch
type Switch struct {
	// id
	Id int32 `json:"id"`
	// 名前
	Name string `json:"name"`
	// 説明
	Description string `json:"description"`
	// スイッチコード
	SwitchCode string `json:"switch_code"`
	Zone SwitchZone `json:"zone"`
	// 接続されているサーバーのインターフェースid
	ServerInterfaces []int32 `json:"server_interfaces"`
	// 接続されている追加ストレージ（NFS）のインターフェースid
	NfsServerInterfaces []int32 `json:"nfs_server_interfaces"`
	ExternalConnection NullableSwitchExternalConnection `json:"external_connection"`
}

type _Switch Switch

// NewSwitch instantiates a new Switch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwitch(id int32, name string, description string, switchCode string, zone SwitchZone, serverInterfaces []int32, nfsServerInterfaces []int32, externalConnection NullableSwitchExternalConnection) *Switch {
	this := Switch{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.SwitchCode = switchCode
	this.Zone = zone
	this.ServerInterfaces = serverInterfaces
	this.NfsServerInterfaces = nfsServerInterfaces
	this.ExternalConnection = externalConnection
	return &this
}

// NewSwitchWithDefaults instantiates a new Switch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwitchWithDefaults() *Switch {
	this := Switch{}
	return &this
}

// GetId returns the Id field value
func (o *Switch) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Switch) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Switch) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Switch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Switch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Switch) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *Switch) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Switch) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Switch) SetDescription(v string) {
	o.Description = v
}

// GetSwitchCode returns the SwitchCode field value
func (o *Switch) GetSwitchCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwitchCode
}

// GetSwitchCodeOk returns a tuple with the SwitchCode field value
// and a boolean to check if the value has been set.
func (o *Switch) GetSwitchCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwitchCode, true
}

// SetSwitchCode sets field value
func (o *Switch) SetSwitchCode(v string) {
	o.SwitchCode = v
}

// GetZone returns the Zone field value
func (o *Switch) GetZone() SwitchZone {
	if o == nil {
		var ret SwitchZone
		return ret
	}

	return o.Zone
}

// GetZoneOk returns a tuple with the Zone field value
// and a boolean to check if the value has been set.
func (o *Switch) GetZoneOk() (*SwitchZone, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zone, true
}

// SetZone sets field value
func (o *Switch) SetZone(v SwitchZone) {
	o.Zone = v
}

// GetServerInterfaces returns the ServerInterfaces field value
func (o *Switch) GetServerInterfaces() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.ServerInterfaces
}

// GetServerInterfacesOk returns a tuple with the ServerInterfaces field value
// and a boolean to check if the value has been set.
func (o *Switch) GetServerInterfacesOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServerInterfaces, true
}

// SetServerInterfaces sets field value
func (o *Switch) SetServerInterfaces(v []int32) {
	o.ServerInterfaces = v
}

// GetNfsServerInterfaces returns the NfsServerInterfaces field value
func (o *Switch) GetNfsServerInterfaces() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.NfsServerInterfaces
}

// GetNfsServerInterfacesOk returns a tuple with the NfsServerInterfaces field value
// and a boolean to check if the value has been set.
func (o *Switch) GetNfsServerInterfacesOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NfsServerInterfaces, true
}

// SetNfsServerInterfaces sets field value
func (o *Switch) SetNfsServerInterfaces(v []int32) {
	o.NfsServerInterfaces = v
}

// GetExternalConnection returns the ExternalConnection field value
// If the value is explicit nil, the zero value for SwitchExternalConnection will be returned
func (o *Switch) GetExternalConnection() SwitchExternalConnection {
	if o == nil || o.ExternalConnection.Get() == nil {
		var ret SwitchExternalConnection
		return ret
	}

	return *o.ExternalConnection.Get()
}

// GetExternalConnectionOk returns a tuple with the ExternalConnection field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Switch) GetExternalConnectionOk() (*SwitchExternalConnection, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalConnection.Get(), o.ExternalConnection.IsSet()
}

// SetExternalConnection sets field value
func (o *Switch) SetExternalConnection(v SwitchExternalConnection) {
	o.ExternalConnection.Set(&v)
}

func (o Switch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Switch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["switch_code"] = o.SwitchCode
	toSerialize["zone"] = o.Zone
	toSerialize["server_interfaces"] = o.ServerInterfaces
	toSerialize["nfs_server_interfaces"] = o.NfsServerInterfaces
	toSerialize["external_connection"] = o.ExternalConnection.Get()
	return toSerialize, nil
}

func (o *Switch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"switch_code",
		"zone",
		"server_interfaces",
		"nfs_server_interfaces",
		"external_connection",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSwitch := _Switch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSwitch)

	if err != nil {
		return err
	}

	*o = Switch(varSwitch)

	return err
}

type NullableSwitch struct {
	value *Switch
	isSet bool
}

func (v NullableSwitch) Get() *Switch {
	return v.value
}

func (v *NullableSwitch) Set(val *Switch) {
	v.value = val
	v.isSet = true
}

func (v NullableSwitch) IsSet() bool {
	return v.isSet
}

func (v *NullableSwitch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwitch(val *Switch) *NullableSwitch {
	return &NullableSwitch{value: val, isSet: true}
}

func (v NullableSwitch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwitch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


