/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakuravps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Disc type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Disc{}

// Disc struct for Disc
type Disc struct {
	// id
	Id int32 `json:"id"`
	// 名前
	Name string `json:"name"`
	// 説明
	Description string `json:"description"`
	// ライセンスが必要かどうか
	LicenseRequired bool `json:"license_required"`
}

type _Disc Disc

// NewDisc instantiates a new Disc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisc(id int32, name string, description string, licenseRequired bool) *Disc {
	this := Disc{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.LicenseRequired = licenseRequired
	return &this
}

// NewDiscWithDefaults instantiates a new Disc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscWithDefaults() *Disc {
	this := Disc{}
	return &this
}

// GetId returns the Id field value
func (o *Disc) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Disc) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Disc) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Disc) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Disc) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Disc) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *Disc) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Disc) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Disc) SetDescription(v string) {
	o.Description = v
}

// GetLicenseRequired returns the LicenseRequired field value
func (o *Disc) GetLicenseRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LicenseRequired
}

// GetLicenseRequiredOk returns a tuple with the LicenseRequired field value
// and a boolean to check if the value has been set.
func (o *Disc) GetLicenseRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LicenseRequired, true
}

// SetLicenseRequired sets field value
func (o *Disc) SetLicenseRequired(v bool) {
	o.LicenseRequired = v
}

func (o Disc) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Disc) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["license_required"] = o.LicenseRequired
	return toSerialize, nil
}

func (o *Disc) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"license_required",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisc := _Disc{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDisc)

	if err != nil {
		return err
	}

	*o = Disc(varDisc)

	return err
}

type NullableDisc struct {
	value *Disc
	isSet bool
}

func (v NullableDisc) Get() *Disc {
	return v.value
}

func (v *NullableDisc) Set(val *Disc) {
	v.value = val
	v.isSet = true
}

func (v NullableDisc) IsSet() bool {
	return v.isSet
}

func (v *NullableDisc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisc(val *Disc) *NullableDisc {
	return &NullableDisc{value: val, isSet: true}
}

func (v NullableDisc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


