/*
さくらのVPS APIドキュメント

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sakura_vps

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PutServerIpv4Ptr200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutServerIpv4Ptr200Response{}

// PutServerIpv4Ptr200Response struct for PutServerIpv4Ptr200Response
type PutServerIpv4Ptr200Response struct {
	// 逆引きホスト名
	Ptr string `json:"ptr"`
}

type _PutServerIpv4Ptr200Response PutServerIpv4Ptr200Response

// NewPutServerIpv4Ptr200Response instantiates a new PutServerIpv4Ptr200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutServerIpv4Ptr200Response(ptr string) *PutServerIpv4Ptr200Response {
	this := PutServerIpv4Ptr200Response{}
	this.Ptr = ptr
	return &this
}

// NewPutServerIpv4Ptr200ResponseWithDefaults instantiates a new PutServerIpv4Ptr200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutServerIpv4Ptr200ResponseWithDefaults() *PutServerIpv4Ptr200Response {
	this := PutServerIpv4Ptr200Response{}
	return &this
}

// GetPtr returns the Ptr field value
func (o *PutServerIpv4Ptr200Response) GetPtr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ptr
}

// GetPtrOk returns a tuple with the Ptr field value
// and a boolean to check if the value has been set.
func (o *PutServerIpv4Ptr200Response) GetPtrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ptr, true
}

// SetPtr sets field value
func (o *PutServerIpv4Ptr200Response) SetPtr(v string) {
	o.Ptr = v
}

func (o PutServerIpv4Ptr200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutServerIpv4Ptr200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ptr"] = o.Ptr
	return toSerialize, nil
}

func (o *PutServerIpv4Ptr200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ptr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutServerIpv4Ptr200Response := _PutServerIpv4Ptr200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutServerIpv4Ptr200Response)

	if err != nil {
		return err
	}

	*o = PutServerIpv4Ptr200Response(varPutServerIpv4Ptr200Response)

	return err
}

type NullablePutServerIpv4Ptr200Response struct {
	value *PutServerIpv4Ptr200Response
	isSet bool
}

func (v NullablePutServerIpv4Ptr200Response) Get() *PutServerIpv4Ptr200Response {
	return v.value
}

func (v *NullablePutServerIpv4Ptr200Response) Set(val *PutServerIpv4Ptr200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePutServerIpv4Ptr200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePutServerIpv4Ptr200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutServerIpv4Ptr200Response(val *PutServerIpv4Ptr200Response) *NullablePutServerIpv4Ptr200Response {
	return &NullablePutServerIpv4Ptr200Response{value: val, isSet: true}
}

func (v NullablePutServerIpv4Ptr200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutServerIpv4Ptr200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


